package id.ias.calculationwaterdebit.util

import id.ias.calculationwaterdebit.database.model.AmbangTipisSegitigaSudutModel
import id.ias.calculationwaterdebit.database.viewmodel.AmbangTipisSegitigaSudutViewModel

class DBAmbangTipisSegitigaSudutUtil {
    companion object {
        fun insertSudutAmbangTipisSegitiga(dao: AmbangTipisSegitigaSudutViewModel, listener: InsertSuccess) {
            dao.deleteAll()
            var koefisiensi = AmbangTipisSegitigaSudutModel(21, (0.000).toFloat(), 21, (2.79).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(22, (0.592).toFloat(), 22, (2.73).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(23 ,(0.591).toFloat(), 23, (2.66).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(24, (0.590).toFloat(), 24, (2.59).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(25,(0.600).toFloat(), 25, (2.53).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(26,(0.590).toFloat(), 26, (2.46).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(27,(0.589).toFloat(), 27, (2.39).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(28,(0.588).toFloat(), 28, (2.33).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(29,(0.588).toFloat(), 29, (2.27).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(30,(0.587).toFloat(), 30, (2.20).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(31,(0.586).toFloat(), 31, (2.15).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(32,(0.586).toFloat(), 32, (2.09).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(33,(0.585).toFloat(), 33, (2.03).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(34,(0.584).toFloat(), 34, (1.98).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(35,(0.584).toFloat(), 35, (1.94).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(36,(0.583).toFloat(), 36, (1.90).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(37,(0.583).toFloat(), 37, (1.85).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(38,(0.582).toFloat(), 38, (1.81).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(39,(0.582).toFloat(), 39, (1.77).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(40,(0.582).toFloat(),40, (1.73).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(41,(0.581).toFloat(), 41, (1.69).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(42,(0.581).toFloat(), 42, (1.65).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(43,(0.580).toFloat(), 43, (1.61).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(44,(0.580).toFloat(),44, (1.58).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(45,(0.580).toFloat(), 45, (1.55).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(46,(0.580).toFloat(), 46, (1.52).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(47,(0.579).toFloat(), 47, (1.49).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(48,(0.579).toFloat(), 48, (1.45).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(49,(0.579).toFloat(), 49, (1.42).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(50,(0.579).toFloat(), 50, (1.39).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(51,(0.578).toFloat(),51, (1.36).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(52,(0.578).toFloat(),52, (1.33).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(53,(0.578).toFloat(), 53, (1.31).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(54,(0.578).toFloat(), 54, (1.28).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(55,(0.578).toFloat(), 55, (1.26).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(56,(0.578).toFloat(), 56, (1.23).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(57,(0.578).toFloat(), 57, (1.21).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(58,(0.578).toFloat(), 58, (1.18).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(59,(0.577).toFloat(), 59, (1.16).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(60,(0.577).toFloat(), 60, (1.14).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(61,(0.577).toFloat(), 61, (1.13).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(62,(0.577).toFloat(),62, (1.10).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(63,(0.577).toFloat(),63, (1.08).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(64,(0.577).toFloat(), 64, (1.06).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(65,(0.577).toFloat(),65, (1.04).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(66,(0.577).toFloat(),66, (1.02).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(67,(0.577).toFloat(), 67, (1.02).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(68,(0.577).toFloat(), 68, (1.00).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(69,(0.577).toFloat(),69, (0.98).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(70,(0.577).toFloat(),70, (0.98).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(71,(0.577).toFloat(),71, (0.96).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(72,(0.577).toFloat(), 72, (0.95).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(73,(0.577).toFloat(),73, (0.94).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(74,(0.577).toFloat(), 74, (0.93).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(75,(0.577).toFloat(), 75, (0.92).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(76,(0.577).toFloat(), 76, (0.91).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(77,(0.578).toFloat(), 77, (0.90).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(78,(0.578).toFloat(),78, (0.89).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(79,(0.578).toFloat(), 79, (0.88).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(80,(0.578).toFloat(), 80, (0.87).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(81,(0.578).toFloat(), 81, (0.87).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(82,(0.578).toFloat(),82, (0.86).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(83,(0.578).toFloat(),83, (0.86).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(84,(0.578).toFloat(), 84, (0.85).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(85,(0.578).toFloat(),85, (0.85).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(86,(0.578).toFloat(), 86, (0.84).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(87,(0.579).toFloat(),87, (0.84).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(88,(0.579).toFloat(), 88, (0.84).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(89,(0.579).toFloat(),89, (0.83).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(90,(0.579).toFloat(),90, (0.83).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(91,(0.579).toFloat(),91, (0.83).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(92,(0.579).toFloat(), 92, (0.82).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(93,(0.580).toFloat(),93, (0.82).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(94,(0.580).toFloat(),94, (0.82).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(95,(0.580).toFloat(),95, (0.81).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(96,(0.580).toFloat(),96, (0.81).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(97, (0.580).toFloat(),97, (0.81).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(98,(0.580).toFloat(),98, (0.80).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(99,(0.581).toFloat(),99, (0.80).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = AmbangTipisSegitigaSudutModel(0 ,(0.0).toFloat(), 100, (0.80).toFloat())
            dao.insert(koefisiensi)
        }
    }

    interface InsertSuccess {
        fun ambangTipisSegitiga(count: Int)
    }
}