package id.ias.calculationwaterdebit.util

import id.ias.calculationwaterdebit.database.dao.KoefisiensiAliranSempurnaDao
import id.ias.calculationwaterdebit.database.model.KoefisiensiAliranSempurnaModel

class DBInjectorUtil {
    companion object {
        suspend fun insertKoefisiensiAliranSempurna(dao: KoefisiensiAliranSempurnaDao) {
            var koefisiensi = KoefisiensiAliranSempurnaModel((0.150).toFloat(), (0.338).toFloat(), (1.49).toFloat(), (0).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.152).toFloat(), (0.338).toFloat(), (1.49).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.160).toFloat(), (0.357).toFloat(), (1.50).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.170).toFloat(), (0.380).toFloat(), (1.50).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.180).toFloat(), (0.403).toFloat(), (1.50).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.190).toFloat(), (0.426).toFloat(), (1.50).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.200).toFloat(), (0.449).toFloat(), (1.50).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.200).toFloat(), (0.449).toFloat(), (1.50).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.210).toFloat(), (0.472).toFloat(), (1.51).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.220).toFloat(), (0.495).toFloat(), (1.51).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.230).toFloat(), (0.519).toFloat(), (1.51).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.240).toFloat(), (0.542).toFloat(), (1.51).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.250).toFloat(), (0.565).toFloat(), (1.51).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.260).toFloat(), (0.589).toFloat(), (1.51).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.270).toFloat(), (0.612).toFloat(), (1.52).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.280).toFloat(), (0.635).toFloat(), (1.52).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.290).toFloat(), (0.659).toFloat(), (1.52).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.300).toFloat(), (0.682).toFloat(), (1.52).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.310).toFloat(), (0.706).toFloat(), (1.52).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.320).toFloat(), (0.729).toFloat(), (1.52).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.330).toFloat(), (0.753).toFloat(), (1.52).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.340).toFloat(), (0.777).toFloat(), (1.53).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.360).toFloat(), (0.824).toFloat(), (1.53).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.370).toFloat(), (0.847).toFloat(), (1.53).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.380).toFloat(), (0.871).toFloat(), (1.53).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.390).toFloat(), (0.895).toFloat(), (1.53).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.400).toFloat(), (0.918).toFloat(), (1.53).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.410).toFloat(), (0.942).toFloat(), (1.53).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.420).toFloat(), (0.966).toFloat(), (1.53).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.430).toFloat(), (0.990).toFloat(), (1.53).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.440).toFloat(), (1.013).toFloat(), (1.54).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.450).toFloat(), (1.037).toFloat(), (1.54).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.460).toFloat(), (1.061).toFloat(), (1.54).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.470).toFloat(), (1.085).toFloat(), (1.54).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.480).toFloat(), (1.085).toFloat(), (1.54).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.490).toFloat(), (1.133).toFloat(), (1.54).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.500).toFloat(), (1.157).toFloat(), (1.54).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.510).toFloat(), (1.180).toFloat(), (1.54).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.520).toFloat(), (1.204).toFloat(), (1.54).toFloat(), (0.6).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.530).toFloat(), (1.228).toFloat(), (1.54).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.540).toFloat(), (1.252).toFloat(), (1.54).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.550).toFloat(), (1.276).toFloat(), (1.54).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.560).toFloat(), (1.300).toFloat(), (1.55).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.570).toFloat(), (1.324).toFloat(), (1.55).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.580).toFloat(), (1.348).toFloat(), (1.55).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.590).toFloat(), (1.372).toFloat(), (1.55).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.600).toFloat(), (1.396).toFloat(), (1.55).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.610).toFloat(), (1.420).toFloat(), (1.55).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.620).toFloat(), (1.444).toFloat(), (1.55).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.630).toFloat(), (1.468).toFloat(), (1.55).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.640).toFloat(), (1.493).toFloat(), (1.55).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.650).toFloat(), (1.517).toFloat(), (1.55).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.660).toFloat(), (1.541).toFloat(), (1.55).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.670).toFloat(), (1.565).toFloat(), (1.55).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.680).toFloat(), (1.589).toFloat(), (1.55).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.690).toFloat(), (1.613).toFloat(), (1.55).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiAliranSempurnaModel((0.700).toFloat(), (1.637).toFloat(), (1.55).toFloat(), (0.7).toFloat())
            dao.insert(koefisiensi)
        }
    }
}