package id.ias.calculationwaterdebit.util

import id.ias.calculationwaterdebit.database.model.KoefisiensiCutThroatedFlumeModel
import id.ias.calculationwaterdebit.database.viewmodel.KoefisiensiCutThroatedFlumeViewModel

class DBKoefisiensiCutThroatedFlumeUtil {
    companion object {
        fun insertKoefisiensiCutThroatedFlume(dao: KoefisiensiCutThroatedFlumeViewModel, listener: InsertSuccess) {
            var koefisiensi = KoefisiensiCutThroatedFlumeModel((0.50).toFloat(),(5.748).toFloat(), (2.065).toFloat(), (0.600).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.51).toFloat(),(5.671).toFloat(), (2.058).toFloat(), (0.602).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.52).toFloat(),(5.598).toFloat(), (2.050).toFloat(), (0.604).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.53).toFloat(),(5.526).toFloat(), (2.043).toFloat(), (0.606).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.54).toFloat(),(5.457).toFloat(), (2.036).toFloat(), (0.607).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.55).toFloat(),(5.390).toFloat(), (2.029).toFloat(), (0.609).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.56).toFloat(),(5.324).toFloat(), (2.023).toFloat(), (0.611).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.57).toFloat(),(5.261).toFloat(), (2.016).toFloat(), (0.613).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.58).toFloat(),(5.200).toFloat(), (2.010).toFloat(), (0.614).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.59).toFloat(),(5.140).toFloat(), (2.004).toFloat(), (0.616).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.60).toFloat(),(5.082).toFloat(), (1.997).toFloat(), (0.618).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.61).toFloat(),(5.026).toFloat(), (1.991).toFloat(), (0.619).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.62).toFloat(),(4.971).toFloat(), (1.985).toFloat(), (0.621).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.63).toFloat(),(4.918).toFloat(), (1.980).toFloat(), (0.623).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.64).toFloat(),(4.866).toFloat(), (1.974).toFloat(), (0.624).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.65).toFloat(),(4.815).toFloat(), (1.968).toFloat(), (0.626).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.66).toFloat(),(4.766).toFloat(), (1.963).toFloat(), (0.627).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.67).toFloat(),(4.717).toFloat(), (1.957).toFloat(), (0.629).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.68).toFloat(),(4.670).toFloat(), (1.952).toFloat(), (0.630).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.69).toFloat(),(4.625).toFloat(), (1.947).toFloat(), (0.632).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.70).toFloat(),(4.580).toFloat(), (1.942).toFloat(), (0.633).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.71).toFloat(),(4.536).toFloat(), (1.937).toFloat(), (0.634).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.72).toFloat(),(4.494).toFloat(), (1.932).toFloat(), (0.636).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.73).toFloat(),(4.452).toFloat(), (1.927).toFloat(), (0.637).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.74).toFloat(),(4.411).toFloat(), (1.922).toFloat(), (0.639).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.75).toFloat(),(4.372).toFloat(), (1.917).toFloat(), (0.640).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.76).toFloat(),(4.333).toFloat(), (1.913).toFloat(), (0.641).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.77).toFloat(),(4.295).toFloat(), (1.908).toFloat(), (0.643).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.78).toFloat(),(4.257).toFloat(), (1.904).toFloat(), (0.644).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.79).toFloat(),(4.221).toFloat(), (1.899).toFloat(), (0.645).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.80).toFloat(),(4.185).toFloat(), (1.895).toFloat(), (0.647).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.81).toFloat(),(4.150).toFloat(), (1.891).toFloat(), (0.648).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.82).toFloat(),(4.116).toFloat(), (1.886).toFloat(), (0.649).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.83).toFloat(),(4.082).toFloat(), (1.882).toFloat(), (0.650).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.84).toFloat(),(4.050).toFloat(), (1.878).toFloat(), (0.652).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.85).toFloat(),(4.017).toFloat(), (1.874).toFloat(), (0.653).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.86).toFloat(),(3.986).toFloat(), (1.870).toFloat(), (0.654).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.87).toFloat(),(3.955).toFloat(), (1.866).toFloat(), (0.655).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.88).toFloat(),(3.924).toFloat(), (1.862).toFloat(), (0.657).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.89).toFloat(),(3.895).toFloat(), (1.858).toFloat(), (0.658).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.90).toFloat(),(3.865).toFloat(), (1.855).toFloat(), (0.659).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.91).toFloat(),(3.837).toFloat(), (1.851).toFloat(), (0.660).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.92).toFloat(),(3.808).toFloat(), (1.847).toFloat(), (0.661).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.93).toFloat(),(3.781).toFloat(), (1.843).toFloat(), (0.662).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.94).toFloat(),(3.754).toFloat(), (1.840).toFloat(), (0.663).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.95).toFloat(),(3.727).toFloat(), (1.836).toFloat(), (0.665).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.96).toFloat(),(3.701).toFloat(), (1.833).toFloat(), (0.666).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.97).toFloat(),(3.675).toFloat(), (1.829).toFloat(), (0.667).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.98).toFloat(),(3.649).toFloat(), (1.826).toFloat(), (0.668).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((0.99).toFloat(),(3.625).toFloat(), (1.822).toFloat(), (0.669).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.00).toFloat(),(3.600).toFloat(), (1.819).toFloat(), (0.670).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.01).toFloat(),(3.576).toFloat(), (1.816).toFloat(), (0.671).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.02).toFloat(),(3.552).toFloat(), (1.813).toFloat(), (0.672).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.03).toFloat(),(3.529).toFloat(), (1.809).toFloat(), (0.673).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.04).toFloat(),(3.506).toFloat(), (1.806).toFloat(), (0.674).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.05).toFloat(),(3.483).toFloat(), (1.803).toFloat(), (0.675).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.06).toFloat(),(3.461).toFloat(), (1.800).toFloat(), (0.676).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.07).toFloat(),(3.439).toFloat(), (1.797).toFloat(), (0.677).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.08).toFloat(),(3.418).toFloat(), (1.794).toFloat(), (0.678).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.09).toFloat(),(3.397).toFloat(), (1.791).toFloat(), (0.679).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.10).toFloat(),(3.376).toFloat(), (1.788).toFloat(), (0.680).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.11).toFloat(),(3.355).toFloat(), (1.785).toFloat(), (0.681).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.12).toFloat(),(3.335).toFloat(), (1.782).toFloat(), (0.682).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.13).toFloat(),(3.315).toFloat(), (1.779).toFloat(), (0.683).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.14).toFloat(),(3.295).toFloat(), (1.776).toFloat(), (0.684).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.15).toFloat(),(3.276).toFloat(), (1.773).toFloat(), (0.685).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.16).toFloat(),(3.257).toFloat(), (1.770).toFloat(), (0.686).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.17).toFloat(),(3.238).toFloat(), (1.768).toFloat(), (0.687).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.18).toFloat(),(3.219).toFloat(), (1.765).toFloat(), (0.688).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.19).toFloat(),(3.201).toFloat(), (1.762).toFloat(), (0.689).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.20).toFloat(),(3.183).toFloat(), (1.759).toFloat(), (0.690).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.21).toFloat(),(3.165).toFloat(), (1.757).toFloat(), (0.691).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.22).toFloat(),(3.148).toFloat(), (1.754).toFloat(), (0.692).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.23).toFloat(),(3.131).toFloat(), (1.751).toFloat(), (0.692).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.24).toFloat(),(3.113).toFloat(), (1.749).toFloat(), (0.693).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.25).toFloat(),(3.097).toFloat(), (1.746).toFloat(), (0.694).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.26).toFloat(),(3.080).toFloat(), (1.744).toFloat(), (0.695).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.27).toFloat(),(3.064).toFloat(), (1.741).toFloat(), (0.696).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.28).toFloat(),(3.047).toFloat(), (1.739).toFloat(), (0.697).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.29).toFloat(),(3.031).toFloat(), (1.736).toFloat(), (0.698).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.30).toFloat(),(3.016).toFloat(), (1.734).toFloat(), (0.699).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.31).toFloat(),(3.000).toFloat(), (1.731).toFloat(), (0.699).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.32).toFloat(),(2.985).toFloat(), (1.729).toFloat(), (0.700).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.33).toFloat(),(2.970).toFloat(), (1.727).toFloat(), (0.701).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.34).toFloat(),(2.955).toFloat(), (1.724).toFloat(), (0.702).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.35).toFloat(),(2.940).toFloat(), (1.722).toFloat(), (0.703).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.36).toFloat(),(2.925).toFloat(), (1.720).toFloat(), (0.704).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.37).toFloat(),(2.911).toFloat(), (1.717).toFloat(), (0.704).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.38).toFloat(),(2.897).toFloat(), (1.715).toFloat(), (0.705).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.39).toFloat(),(2.882).toFloat(), (1.713).toFloat(), (0.706).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.40).toFloat(),(2.869).toFloat(), (1.710).toFloat(), (0.707).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.41).toFloat(),(2.855).toFloat(), (1.708).toFloat(), (0.708).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.42).toFloat(),(2.841).toFloat(), (1.706).toFloat(), (0.708).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.43).toFloat(),(2.828).toFloat(), (1.704).toFloat(), (0.709).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.44).toFloat(),(2.815).toFloat(), (1.702).toFloat(), (0.710).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.45).toFloat(),(2.801).toFloat(), (1.700).toFloat(), (0.711).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.46).toFloat(),(2.788).toFloat(), (1.697).toFloat(), (0.712).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.47).toFloat(),(2.776).toFloat(), (1.695).toFloat(), (0.712).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.48).toFloat(),(2.763).toFloat(), (1.693).toFloat(), (0.713).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.49).toFloat(),(2.750).toFloat(), (1.691).toFloat(), (0.714).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.50).toFloat(),(2.738).toFloat(), (1.689).toFloat(), (0.715).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.51).toFloat(),(2.726).toFloat(), (1.687).toFloat(), (0.715).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.52).toFloat(),(2.714).toFloat(), (1.685).toFloat(), (0.716).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.53).toFloat(),(2.702).toFloat(), (1.683).toFloat(), (0.717).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.54).toFloat(),(2.690).toFloat(), (1.681).toFloat(), (0.718).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.55).toFloat(),(2.678).toFloat(), (1.679).toFloat(), (0.718).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.56).toFloat(),(2.667).toFloat(), (1.677).toFloat(), (0.719).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.57).toFloat(),(2.655).toFloat(), (1.675).toFloat(), (0.720).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.58).toFloat(),(2.644).toFloat(), (1.673).toFloat(), (0.721).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.59).toFloat(),(2.632).toFloat(), (1.671).toFloat(), (0.721).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.60).toFloat(),(2.621).toFloat(), (1.669).toFloat(), (0.722).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.61).toFloat(),(2.610).toFloat(), (1.667).toFloat(), (0.723).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.62).toFloat(),(2.599).toFloat(), (1.665).toFloat(), (0.723).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.63).toFloat(),(2.589).toFloat(), (1.664).toFloat(), (0.724).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.64).toFloat(),(2.578).toFloat(), (1.662).toFloat(), (0.725).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.65).toFloat(),(2.567).toFloat(), (1.660).toFloat(), (0.726).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.66).toFloat(),(2.557).toFloat(), (1.658).toFloat(), (0.726).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.67).toFloat(),(2.547).toFloat(), (1.656).toFloat(), (0.727).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.68).toFloat(),(2.536).toFloat(), (1.654).toFloat(), (0.728).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.69).toFloat(),(2.526).toFloat(), (1.653).toFloat(), (0.728).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.70).toFloat(),(2.516).toFloat(), (1.651).toFloat(), (0.729).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.71).toFloat(),(2.506).toFloat(), (1.649).toFloat(), (0.730).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.72).toFloat(),(2.496).toFloat(), (1.647).toFloat(), (0.730).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.73).toFloat(),(2.487).toFloat(), (1.645).toFloat(), (0.731).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.74).toFloat(),(2.477).toFloat(), (1.644).toFloat(), (0.732).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.75).toFloat(),(2.467).toFloat(), (1.642).toFloat(), (0.732).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.76).toFloat(),(2.458).toFloat(), (1.640).toFloat(), (0.733).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.77).toFloat(),(2.449).toFloat(), (1.639).toFloat(), (0.734).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.78).toFloat(),(2.439).toFloat(), (1.637).toFloat(), (0.734).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.79).toFloat(),(2.430).toFloat(), (1.635).toFloat(), (0.735).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.80).toFloat(),(2.421).toFloat(), (1.634).toFloat(), (0.736).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.81).toFloat(),(2.412).toFloat(), (1.632).toFloat(), (0.736).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.82).toFloat(),(2.403).toFloat(), (1.630).toFloat(), (0.737).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.83).toFloat(),(2.394).toFloat(), (1.629).toFloat(), (0.738).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.84).toFloat(),(2.385).toFloat(), (1.627).toFloat(), (0.738).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.85).toFloat(),(2.377).toFloat(), (1.625).toFloat(), (0.739).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.86).toFloat(),(2.368).toFloat(), (1.624).toFloat(), (0.739).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.87).toFloat(),(2.359).toFloat(), (1.622).toFloat(), (0.740).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.88).toFloat(),(2.351).toFloat(), (1.621).toFloat(), (0.741).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.89).toFloat(),(2.343).toFloat(), (1.619).toFloat(), (0.741).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.90).toFloat(),(2.334).toFloat(), (1.618).toFloat(), (0.742).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.91).toFloat(),(2.326).toFloat(), (1.616).toFloat(), (0.743).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.92).toFloat(),(2.318).toFloat(), (1.614).toFloat(), (0.743).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.93).toFloat(),(2.310).toFloat(), (1.613).toFloat(), (0.744).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.94).toFloat(),(2.302).toFloat(), (1.611).toFloat(), (0.744).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.95).toFloat(),(2.294).toFloat(), (1.610).toFloat(), (0.745).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.96).toFloat(),(2.286).toFloat(), (1.608).toFloat(), (0.746).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.97).toFloat(),(2.278).toFloat(), (1.607).toFloat(), (0.746).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.98).toFloat(),(2.270).toFloat(), (1.605).toFloat(), (0.747).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((1.99).toFloat(),(2.262).toFloat(), (1.604).toFloat(), (0.747).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.00).toFloat(),(2.255).toFloat(), (1.602).toFloat(), (0.748).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.01).toFloat(),(2.247).toFloat(), (1.601).toFloat(), (0.749).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.02).toFloat(),(2.240).toFloat(), (1.599).toFloat(), (0.749).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.03).toFloat(),(2.232).toFloat(), (1.598).toFloat(), (0.750).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.04).toFloat(),(2.225).toFloat(), (1.597).toFloat(), (0.750).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.05).toFloat(),(2.218).toFloat(), (1.595).toFloat(), (0.751).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.06).toFloat(),(2.210).toFloat(), (1.594).toFloat(), (0.752).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.07).toFloat(),(2.203).toFloat(), (1.592).toFloat(), (0.752).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.08).toFloat(),(2.196).toFloat(), (1.591).toFloat(), (0.753).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.09).toFloat(),(2.189).toFloat(), (1.590).toFloat(), (0.753).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.10).toFloat(),(2.182).toFloat(), (1.588).toFloat(), (0.754).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.11).toFloat(),(2.175).toFloat(), (1.587).toFloat(), (0.754).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.12).toFloat(),(2.168).toFloat(), (1.585).toFloat(), (0.755).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.13).toFloat(),(2.161).toFloat(), (1.584).toFloat(), (0.756).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.14).toFloat(),(2.154).toFloat(), (1.583).toFloat(), (0.756).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.15).toFloat(),(2.147).toFloat(), (1.581).toFloat(), (0.757).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.16).toFloat(),(2.141).toFloat(), (1.580).toFloat(), (0.757).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.17).toFloat(),(2.134).toFloat(), (1.579).toFloat(), (0.758).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.18).toFloat(),(2.127).toFloat(), (1.577).toFloat(), (0.758).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.19).toFloat(),(2.121).toFloat(), (1.576).toFloat(), (0.759).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.20).toFloat(),(2.114).toFloat(), (1.575).toFloat(), (0.759).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.21).toFloat(),(2.108).toFloat(), (1.573).toFloat(), (0.760).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.22).toFloat(),(2.101).toFloat(), (1.572).toFloat(), (0.761).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.23).toFloat(),(2.095).toFloat(), (1.571).toFloat(), (0.761).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.24).toFloat(),(2.089).toFloat(), (1.569).toFloat(), (0.762).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.25).toFloat(),(2.082).toFloat(), (1.568).toFloat(), (0.762).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.26).toFloat(),(2.076).toFloat(), (1.567).toFloat(), (0.763).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.27).toFloat(),(2.070).toFloat(), (1.566).toFloat(), (0.763).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.28).toFloat(),(2.064).toFloat(), (1.564).toFloat(), (0.764).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.29).toFloat(),(2.058).toFloat(), (1.563).toFloat(), (0.764).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.30).toFloat(),(2.052).toFloat(), (1.562).toFloat(), (0.765).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.31).toFloat(),(2.046).toFloat(), (1.561).toFloat(), (0.765).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.32).toFloat(),(2.040).toFloat(), (1.559).toFloat(), (0.766).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.33).toFloat(),(2.034).toFloat(), (1.558).toFloat(), (0.766).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.34).toFloat(),(2.028).toFloat(), (1.557).toFloat(), (0.767).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.35).toFloat(),(2.022).toFloat(), (1.556).toFloat(), (0.767).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.36).toFloat(),(2.016).toFloat(), (1.555).toFloat(), (0.768).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.37).toFloat(),(2.011).toFloat(), (1.553).toFloat(), (0.769).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.38).toFloat(),(2.005).toFloat(), (1.552).toFloat(), (0.769).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.39).toFloat(),(1.999).toFloat(), (1.551).toFloat(), (0.770).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.40).toFloat(),(1.994).toFloat(), (1.550).toFloat(), (0.770).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.41).toFloat(),(1.988).toFloat(), (1.549).toFloat(), (0.771).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.42).toFloat(),(1.983).toFloat(), (1.547).toFloat(), (0.771).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.43).toFloat(),(1.977).toFloat(), (1.546).toFloat(), (0.772).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.44).toFloat(),(1.972).toFloat(), (1.545).toFloat(), (0.772).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.45).toFloat(),(1.966).toFloat(), (1.544).toFloat(), (0.773).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.46).toFloat(),(1.961).toFloat(), (1.543).toFloat(), (0.773).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.47).toFloat(),(1.955).toFloat(), (1.542).toFloat(), (0.774).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.48).toFloat(),(1.950).toFloat(), (1.541).toFloat(), (0.774).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.49).toFloat(),(1.945).toFloat(), (1.539).toFloat(), (0.775).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.50).toFloat(),(1.940).toFloat(), (1.538).toFloat(), (0.775).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.51).toFloat(),(1.934).toFloat(), (1.537).toFloat(), (0.776).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.52).toFloat(),(1.929).toFloat(), (1.536).toFloat(), (0.776).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.53).toFloat(),(1.924).toFloat(), (1.535).toFloat(), (0.777).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.54).toFloat(),(1.919).toFloat(), (1.534).toFloat(), (0.777).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.55).toFloat(),(1.914).toFloat(), (1.533).toFloat(), (0.778).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.56).toFloat(),(1.909).toFloat(), (1.532).toFloat(), (0.778).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.57).toFloat(),(1.904).toFloat(), (1.531).toFloat(), (0.778).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.58).toFloat(),(1.899).toFloat(), (1.529).toFloat(), (0.779).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.59).toFloat(),(1.894).toFloat(), (1.528).toFloat(), (0.779).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.60).toFloat(),(1.889).toFloat(), (1.527).toFloat(), (0.780).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.61).toFloat(),(1.884).toFloat(), (1.526).toFloat(), (0.780).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.62).toFloat(),(1.879).toFloat(), (1.525).toFloat(), (0.781).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.63).toFloat(),(1.874).toFloat(), (1.524).toFloat(), (0.781).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.64).toFloat(),(1.869).toFloat(), (1.523).toFloat(), (0.782).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.65).toFloat(),(1.865).toFloat(), (1.522).toFloat(), (0.782).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.66).toFloat(),(1.860).toFloat(), (1.521).toFloat(), (0.783).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.67).toFloat(),(1.855).toFloat(), (1.520).toFloat(), (0.783).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.68).toFloat(),(1.851).toFloat(), (1.519).toFloat(), (0.784).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.69).toFloat(),(1.846).toFloat(), (1.518).toFloat(), (0.784).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.70).toFloat(),(1.841).toFloat(), (1.517).toFloat(), (0.785).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.71).toFloat(),(1.837).toFloat(), (1.516).toFloat(), (0.785).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.72).toFloat(),(1.832).toFloat(), (1.515).toFloat(), (0.786).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.73).toFloat(),(1.828).toFloat(), (1.514).toFloat(), (0.786).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.74).toFloat(),(1.823).toFloat(), (1.513).toFloat(), (0.786).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = KoefisiensiCutThroatedFlumeModel((2.75).toFloat(),(1.819).toFloat(), (1.512).toFloat(), (0.787).toFloat())
            dao.insert(koefisiensi)
            listener.koefisiensiCutThroatedFlume(0)
        }
    }

    interface InsertSuccess {
        fun koefisiensiCutThroatedFlume(count: Int)
    }
}