package id.ias.calculationwaterdebit.util

import id.ias.calculationwaterdebit.database.model.MercuAmbangModel
import id.ias.calculationwaterdebit.database.viewmodel.MercuAmbangViewModel

class DBMercuAmbangUtil {
    companion object {
        fun insertMercuAmbang(dao: MercuAmbangViewModel, listener: InsertSuccess) {
            var koefisiensi = MercuAmbangModel((0.11).toFloat(), (0.0024).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.12).toFloat(), (0.0024).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.13).toFloat(), (0.0024).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.14).toFloat(), (0.0024).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.15).toFloat(), (0.0024).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.16).toFloat(), (0.0024).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.17).toFloat(), (0.0024).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.18).toFloat(), (0.0024).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.19).toFloat(), (0.0024).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.20).toFloat(), (0.0024).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.21).toFloat(), (0.0024).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.22).toFloat(), (0.0024).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.23).toFloat(), (0.0024).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.24).toFloat(), (0.0024).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.25).toFloat(), (0.0024).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.26).toFloat(), (0.0024).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.27).toFloat(), (0.0025).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.28).toFloat(), (0.0025).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.29).toFloat(), (0.0025).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.30).toFloat(), (0.0025).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.31).toFloat(), (0.0025).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.32).toFloat(), (0.0025).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.33).toFloat(), (0.0025).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.34).toFloat(), (0.0026).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.35).toFloat(), (0.0026).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.36).toFloat(), (0.0026).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.37).toFloat(), (0.0026).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.38).toFloat(), (0.0027).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.39).toFloat(), (0.0027).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.40).toFloat(), (0.0027).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.41).toFloat(), (0.0027).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.42).toFloat(), (0.0028).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.43).toFloat(), (0.0028).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.44).toFloat(), (0.0028).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.45).toFloat(), (0.0028).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.46).toFloat(), (0.0029).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.47).toFloat(), (0.0029).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.48).toFloat(), (0.0029).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.49).toFloat(), (0.0030).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.50).toFloat(), (0.0030).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.51).toFloat(), (0.0031).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.52).toFloat(), (0.0031).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.53).toFloat(), (0.0033).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.54).toFloat(), (0.0033).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.55).toFloat(), (0.0034).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.56).toFloat(), (0.0035).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.57).toFloat(), (0.0036).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.58).toFloat(), (0.0036).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.59).toFloat(), (0.0037).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.60).toFloat(), (0.0037).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.61).toFloat(), (0.0038).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.62).toFloat(), (0.0038).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.63).toFloat(), (0.0039).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.64).toFloat(), (0.0040).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.65).toFloat(), (0.0041).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.66).toFloat(), (0.0042).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.67).toFloat(), (0.0042).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.68).toFloat(), (0.0043).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.69).toFloat(), (0.0043).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.70).toFloat(), (0.0044).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.71).toFloat(), (0.0044).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.72).toFloat(), (0.0045).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.73).toFloat(), (0.0045).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.74).toFloat(), (0.0045).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.75).toFloat(), (0.0045).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.76).toFloat(), (0.0045).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.77).toFloat(), (0.0045).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.78).toFloat(), (0.0044).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.79).toFloat(), (0.0043).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.80).toFloat(), (0.0042).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.81).toFloat(), (0.0041).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.82).toFloat(), (0.0039).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.83).toFloat(), (0.0038).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.84).toFloat(), (0.0036).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.85).toFloat(), (0.0034).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.86).toFloat(), (0.0031).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.87).toFloat(), (0.0029).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.88).toFloat(), (0.0027).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.89).toFloat(), (0.0024).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.90).toFloat(), (0.0021).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.91).toFloat(), (0.0018).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.92).toFloat(), (0.0015).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.93).toFloat(), (0.0012).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.94).toFloat(), (0.0009).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.95).toFloat(), (0.0006).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.96).toFloat(), (0.0003).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.97).toFloat(), (0.0000).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.98).toFloat(), (-0.0003).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((0.99).toFloat(), (-0.0005).toFloat())
            dao.insert(koefisiensi)
            koefisiensi = MercuAmbangModel((1.00).toFloat(), (-0.0010).toFloat())
            dao.insert(koefisiensi)
            listener.mercuAmbang(0)
        }
    }

    interface InsertSuccess {
        fun mercuAmbang(count: Int)
    }
}